FROM node:20

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
COPY package.json ./
RUN npm install

# Copy app files
COPY app/ ./app

# Set working directory inside app
WORKDIR /usr/src/app/app

# Expose port
EXPOSE 3000

# Start the app
CMD ["npm", "start"]